import { Building2 } from 'lucide-react'
import { fmtDate } from '../../lib/helpers'

export default function EnterpriseReportHeader({ company, report, filters, generatedBy }) {
  const companyName = company?.software_name || company?.name || 'Aura Stay ERP'
  const resortName = company?.name || 'Novem Eco Resort'
  const rawPropertyName = filters?.property && filters.property !== 'All Properties'
    ? filters.property
    : resortName
  const propertyName = rawPropertyName && rawPropertyName !== 'All Properties'
    ? rawPropertyName
    : ''
  const generatedAt = new Date().toLocaleString([], {
    year: 'numeric',
    month: 'short',
    day: '2-digit',
    hour: '2-digit',
    minute: '2-digit',
  })
  const dateFrom = filters?.dateFrom ? fmtDate(filters.dateFrom) : ''
  const dateTo = filters?.dateTo ? fmtDate(filters.dateTo) : ''
  const periodLabel = dateFrom && dateTo && dateFrom !== dateTo
    ? `For the period ${dateFrom} - ${dateTo}`
    : dateTo
      ? `As at ${dateTo}`
      : report.reportCategory

  return (
    <section className="enterprise-report-header">
      <div className="erp-header-brand">
        <div className="erp-brand-left">
          <div className="erp-logo-box">
            {company?.logo_url ? <img src={company.logo_url} alt={resortName} /> : <Building2 size={18} />}
          </div>
          <div className="erp-company-block">
            <p className="erp-company">{resortName}</p>
            <p className="erp-property">{[propertyName, companyName].filter(Boolean).join(' · ')}</p>
          </div>
        </div>
        <div className="erp-title-block">
          <h1>{report.name}</h1>
          <p className="erp-report-period">{periodLabel}</p>
        </div>
      </div>
      <div className="erp-header-meta">
        <span>Currency: {filters.currency || 'BDT'} (৳)</span>
        <span>Generated: {generatedAt}</span>
        {generatedBy ? <span>Generated by: {generatedBy}</span> : null}
      </div>
      {report.ifrsReference && (
        <div className="erp-ifrs-note">
          <b>{report.ifrsReference}</b> {report.ifrsNote}
        </div>
      )}
    </section>
  )
}
