export default function EnterpriseReportFooter({
  generatedBy,
  generatedTime,
  currency,
  rounding,
  pageNumber,
  printedBy,
  printedTime,
  pageLabel,
}) {
  const items = [
    { label: 'Generated By', value: generatedBy || printedBy || 'System' },
    { label: 'Generated Time', value: generatedTime || printedTime || '—' },
    { label: 'Currency', value: currency || 'BDT' },
    { label: 'Rounding', value: rounding || '0.00' },
    { label: 'Page Number', value: pageNumber || pageLabel || '1 of 1' },
  ]

  return (
    <footer className="rounded-3xl border border-slate-200 bg-white px-6 py-4 shadow-sm">
      <dl className="grid gap-4 md:grid-cols-3 xl:grid-cols-5">
        {items.map((item) => (
          <div key={item.label} className="space-y-1">
            <dt className="text-xs font-semibold uppercase tracking-[0.08em] text-slate-500">{item.label}</dt>
            <dd className="text-sm font-medium text-slate-900">{item.value}</dd>
          </div>
        ))}
      </dl>
    </footer>
  )
}
