import { exportXLSX, fmtBDT, fmtDate } from '../helpers'

const escapeCsv = (value) => {
  const raw = value == null ? '' : String(value)
  return /[",\n]/.test(raw) ? `"${raw.replaceAll('"', '""')}"` : raw
}

const formatCell = (value, column) => {
  if (column?.type === 'currency') return Number(value || 0).toFixed(2)
  if (column?.type === 'date') return value ? fmtDate(value) : ''
  if (column?.type === 'percent') return `${Number(value || 0).toFixed(2)}%`
  return value ?? ''
}

const statusTone = (value) => {
  const text = String(value || '').toLowerCase()
  if (/cancel|dirty|void|failed|overdue/.test(text)) return 'danger'
  if (/pending|inspect|hold|draft/.test(text)) return 'warning'
  if (/complete|checked|bill|posted|transfer/.test(text)) return 'info'
  if (/clean|settled|confirm|approve|balanced|open/.test(text)) return 'success'
  return 'neutral'
}

export function getReportPrintSettings(report = {}) {
  const columns = Array.isArray(report?.columns) ? report.columns : []
  const explicitOrientation = report?.printOrientation
  const totalColumnWidth = columns.reduce((sum, column) => sum + Number(column?.width || 120), 0)
  const orientation = explicitOrientation === 'landscape' || explicitOrientation === 'portrait'
    ? explicitOrientation
    : totalColumnWidth > 1180 || columns.length > 10
      ? 'landscape'
      : 'portrait'

  return {
    pageSize: 'A4',
    orientation,
    title: `A4 ${orientation === 'landscape' ? 'Landscape' : 'Portrait'}`,
    portalType: orientation === 'landscape' ? 'A4-landscape' : 'A4',
    printClass: orientation === 'landscape' ? 'print-a4-landscape' : 'print-a4-portrait',
  }
}

export function buildReportRows(report, rows, totals = {}, meta = {}) {
  const headerRows = [
    [meta.companyName || 'Aura Stay', meta.propertyName || 'All Properties'],
    [report.name, report.reportCategory],
    [`Period: ${fmtDate(meta.dateFrom)} to ${fmtDate(meta.dateTo)}`, `Currency: ${meta.currency || 'BDT'}`],
    [`Generated: ${new Date().toLocaleString()}`, `Generated by: ${meta.generatedBy || 'System'}`],
    [],
  ]
  const tableRows = [
    report.columns.map((col) => col.label),
    ...rows.map((row) => report.columns.map((col) => formatCell(row[col.key], col))),
  ]
  const totalRow = report.columns.map((col, index) => {
    if (index === 0) return 'Grand Total'
    if (col.total) return Number(totals[col.key] || 0).toFixed(2)
    return ''
  })
  return [...headerRows, ...tableRows, totalRow]
}

export function exportReportCsv(report, rows, totals, meta) {
  const allRows = buildReportRows(report, rows, totals, meta)
  const csv = allRows.map((row) => row.map(escapeCsv).join(',')).join('\n')
  const blob = new Blob([csv], { type: 'text/csv;charset=utf-8;' })
  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = url
  a.download = `${report.code}_${meta.dateFrom}_to_${meta.dateTo}.csv`
  document.body.appendChild(a)
  a.click()
  document.body.removeChild(a)
  URL.revokeObjectURL(url)
}

export function exportReportExcel(report, rows, totals, meta) {
  return exportXLSX(`${report.code}_${meta.dateFrom}_to_${meta.dateTo}.xlsx`, [
    { name: report.code, rows: buildReportRows(report, rows, totals, meta) },
  ])
}

export function exportReportPdf(report, rows, totals, meta) {
  const columns = report.columns
  const printSettings = getReportPrintSettings(report)
  const amount = (v) => fmtBDT(v)
  const tableHead = columns.map((col) => `<th style="text-align:${col.align || 'left'}">${col.label}</th>`).join('')
  const tableBody = rows.map((row) => `<tr>${columns.map((col) => {
    const raw = row[col.key]
    const val = col.type === 'currency'
      ? amount(raw)
      : col.type === 'status'
        ? `<span class="status ${statusTone(raw)}">${raw || '-'}</span>`
        : formatCell(raw, col)
    return `<td style="text-align:${col.align || 'left'}">${val}</td>`
  }).join('')}</tr>`).join('')
  const totalRow = `<tr class="grand">${columns.map((col, index) => {
    const val = index === 0 ? 'Grand Total' : col.total ? amount(totals[col.key]) : ''
    return `<td style="text-align:${col.align || 'left'}">${val}</td>`
  }).join('')}</tr>`
  const win = window.open('', '_blank', 'width=1440,height=900')
  if (!win) return
  win.document.write(`
    <html>
      <head>
        <title>${report.name}</title>
        <style>
          @page { size: A4 ${printSettings.orientation}; margin: 10mm; }
          body { font-family: Arial, sans-serif; color: #060606; margin:0; font-size: 11px; }
          .top { border-bottom: 2px solid #151515; padding-bottom: 10px; margin-bottom: 9px; }
          .brand { display:grid; grid-template-columns: 1fr auto; gap: 24px; align-items:start; }
          .brand-left { display:grid; grid-template-columns: 30px 1fr; gap: 9px; align-items:center; }
          .mark { width:30px; height:30px; border-radius:6px; display:grid; place-items:center; background:#eaf3d9; color:#506f00; font-weight:800; }
          .brand h2 { margin:0; font-size:14px; line-height:1.05; }
          .brand small, .meta, footer { color:#5f6970; font-size:10px; }
          .title { text-align:right; }
          .brand h1 { margin:0; font-size:17px; line-height:1.1; }
          .meta { display:flex; justify-content:space-between; gap:16px; padding:9px 0 18px; }
          table { width:100%; border-collapse: collapse; table-layout: fixed; font-size: 9px; line-height:1.22; }
          thead { display: table-header-group; }
          tfoot { display: table-row-group; }
          th { color:#4d555b; border-bottom:1px solid #d0cdc2; padding:6px 5px; font-weight:700; text-transform:uppercase; overflow-wrap:anywhere; }
          td { border-bottom:1px solid #ebe8df; padding:6px 5px; overflow-wrap:anywhere; vertical-align:top; }
          .grand td { border-bottom:0; padding-top:10px; font-weight:700; text-transform:uppercase; }
          .status { display:inline-flex; min-height:16px; align-items:center; padding:2px 8px; border-radius:5px; font-size:10px; line-height:1.1; white-space:nowrap; }
          .status.success { background:#eaf3d9; color:#2d6100; }
          .status.info { background:#e5f0fb; color:#23517b; }
          .status.warning { background:#fff0d8; color:#7a4a00; }
          .status.danger { background:#fde8e7; color:#8a2b27; }
          .status.neutral { background:#efeee9; color:#4d555b; }
          .sign { display:grid; grid-template-columns: repeat(3, 1fr); gap: 40px; margin-top: 42px; font-size: 10px; break-inside: avoid; color:#5f6970; }
          .sign div { border-top:1px solid #7b7f79; padding-top:8px; text-align:center; }
          footer { position: fixed; bottom: 0; left: 0; right: 0; display:flex; justify-content:space-between; border-top:1px solid #dedbd1; padding-top:10px; }
        </style>
      </head>
      <body>
        <section class="top">
          <div class="brand">
            <div class="brand-left">
              <div class="mark">⌂</div>
              <div>
                <h2>${meta.propertyName || meta.companyName || 'Novem Eco Resort'}</h2>
                <small>${meta.companyName || 'Aura Stay ERP'}</small>
              </div>
            </div>
            <div class="title">
              <h1>${report.name}</h1>
              <small>${fmtDate(meta.dateFrom)} to ${fmtDate(meta.dateTo)}</small>
            </div>
          </div>
        </section>
        <div class="meta">
          <span>Currency: ${meta.currency || 'BDT'} (৳)</span>
          <span>Generated: ${new Date().toLocaleString()}</span>
        </div>
        <table><thead><tr>${tableHead}</tr></thead><tbody>${tableBody}${totalRow}</tbody></table>
        <section class="sign"><div>Prepared by</div><div>Reviewed by</div><div>Approved by</div></section>
        <footer><span>Aura Stay ERP · Confidential</span><span>Page 1 of 1</span></footer>
        <script>window.onload = () => window.print()</script>
      </body>
    </html>
  `)
  win.document.close()
}
