import ExcelJS from 'exceljs'

const escapeCsv = (value) => {
  const raw = value == null ? '' : String(value)
  return /[",\n]/.test(raw) ? `"${raw.replaceAll('"', '""')}"` : raw
}

const colKey = (col) => (typeof col === 'string' ? col : col.key)
const colLabel = (col) => (typeof col === 'string' ? col : col.label)
const colAlign = (col) => (typeof col === 'object' ? col.align || 'left' : 'left')

export function toCsv(reportPayload) {
  const { report, rows, totals } = reportPayload
  const columns = report.columns
  const data = [
    [report.name],
    [`Category: ${report.category}`],
    [],
    columns.map(colLabel),
    ...rows.map((row) => columns.map((col) => row[colKey(col)] ?? '')),
    columns.map((col, index) => index === 0 ? 'Grand Total' : totals[colKey(col)] ?? ''),
  ]
  return data.map((row) => row.map(escapeCsv).join(',')).join('\n')
}

export async function toExcel(reportPayload) {
  const { report, rows, totals } = reportPayload
  const columns = report.columns
  const workbook = new ExcelJS.Workbook()
  const sheet = workbook.addWorksheet(report.code)
  sheet.addRow([report.name])
  sheet.addRow([`Category: ${report.category}`])
  sheet.addRow([])
  sheet.addRow(columns.map(colLabel))
  rows.forEach((row) => sheet.addRow(columns.map((col) => row[colKey(col)] ?? '')))
  sheet.addRow(columns.map((col, index) => index === 0 ? 'Grand Total' : totals[colKey(col)] ?? ''))
  sheet.views = [{ state: 'frozen', ySplit: 4 }]
  sheet.getRow(4).font = { bold: true, color: { argb: 'FFFFFFFF' } }
  sheet.getRow(4).fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FF0F3A5F' } }
  sheet.columns.forEach((column) => { column.width = 18 })
  return workbook.xlsx.writeBuffer()
}

export function toPdfHtml(reportPayload) {
  const { report, rows, totals, filters, audit } = reportPayload
  const columns = report.columns
  const head = columns.map((col) => `<th style="text-align:${colAlign(col)}">${colLabel(col)}</th>`).join('')
  const body = rows.map((row) => `<tr>${columns.map((col) => `<td style="text-align:${colAlign(col)}">${row[colKey(col)] ?? ''}</td>`).join('')}</tr>`).join('')
  const total = `<tr class="grand">${columns.map((col, index) => `<td style="text-align:${colAlign(col)}">${index === 0 ? 'Grand Total' : totals[colKey(col)] ?? ''}</td>`).join('')}</tr>`
  return `<!doctype html>
    <html>
      <head>
        <meta charset="utf-8" />
        <style>
          @page { size: A4 landscape; margin: 10mm; }
          body { font-family: Arial, sans-serif; color: #102033; }
          header { border: 2px solid #0f3a5f; padding: 10px; text-align: center; margin-bottom: 8px; }
          table { width: 100%; border-collapse: collapse; font-size: 9px; }
          thead { display: table-header-group; }
          th { background: #0f3a5f; color: white; }
          th, td { border: 1px solid #c9d9e8; padding: 5px; }
          tr:nth-child(even) td { background: #f8fbff; }
          .grand td { background: #dbeafe; font-weight: 700; }
          .sign { display: grid; grid-template-columns: repeat(4, 1fr); gap: 12px; margin-top: 20px; font-size: 9px; }
          .sign div { border-top: 1px solid #0f172a; padding-top: 5px; text-align: center; }
          footer { position: fixed; bottom: 0; left: 0; right: 0; text-align: center; font-size: 9px; color: #64748b; }
        </style>
      </head>
      <body>
        <header>
          <h1>${report.name}</h1>
          <p>${report.category} | ${filters?.dateFrom || ''} to ${filters?.dateTo || ''}</p>
          <p>Generated by ${audit?.generatedBy || 'system'} at ${audit?.generatedAt || new Date().toISOString()}</p>
        </header>
        <table><thead><tr>${head}</tr></thead><tbody>${body}${total}</tbody></table>
        <section class="sign"><div>Prepared by</div><div>Checked by</div><div>Approved by</div><div>Printed by: ${audit?.generatedBy || ''}</div></section>
        <footer>This report is system generated and intended for internal use only.</footer>
      </body>
    </html>`
}
