export const reportCategories = [
  { code: 'IFRS', name: 'IFRS Financial Reports', sort_order: 10 },
  { code: 'HOTEL_KPI', name: 'Hotel KPI & Operations', sort_order: 20 },
  { code: 'POS', name: 'Restaurant POS', sort_order: 30 },
  { code: 'ACCOUNTING', name: 'Accounting Control', sort_order: 40 },
]

export const standardFilters = [
  'dateFrom', 'dateTo', 'property', 'outlet', 'department', 'costCenter',
  'roomType', 'guestType', 'reservationSource', 'paymentMethod', 'status', 'user', 'currency',
]

export const standardColumns = [
  'slNo', 'transactionDate', 'documentNo', 'voucherNo', 'reservationNo', 'guestId',
  'guestName', 'roomNo', 'roomType', 'department', 'costCenter', 'accountCode',
  'accountName', 'description', 'quantity', 'rate', 'grossAmount', 'discount',
  'vat', 'serviceCharge', 'netAmount', 'debit', 'credit', 'balance', 'paymentMethod',
  'createdBy', 'approvedBy', 'status', 'remarks',
]

const template = (code, name, category, overrides = {}) => ({
  code,
  name,
  category,
  columns: overrides.columns || standardColumns,
  filters: overrides.filters || standardFilters,
  kpis: overrides.kpis || ['totalRevenue', 'netAmount', 'outstandingReceivable'],
  dataSource: overrides.dataSource || 'reporting.vw_enterprise_report_rows',
  grouping: overrides.grouping || 'department',
  sorting: overrides.sorting || [{ key: 'transactionDate', direction: 'desc' }],
  ifrsReference: overrides.ifrsReference || null,
  exportPermission: true,
  printPermission: true,
})

export const reportTemplates = [
  template('IFRS-SFP', 'Statement of Financial Position', 'IFRS', { ifrsReference: 'IAS 1', grouping: 'classification' }),
  template('IFRS-PNL', 'Statement of Profit or Loss', 'IFRS', { ifrsReference: 'IAS 1', grouping: 'statementLine' }),
  template('IFRS-CFS', 'Statement of Cash Flows', 'IFRS', { ifrsReference: 'IAS 7', grouping: 'cashFlowClass' }),
  template('IFRS-SCE', 'Statement of Changes in Equity', 'IFRS', { ifrsReference: 'IAS 1', grouping: 'equityComponent' }),
  template('IFRS-REV-REC', 'Revenue Recognition Report', 'IFRS', { ifrsReference: 'IFRS 15', grouping: 'performanceObligation' }),
  template('IFRS-DEF-REV', 'Deferred Revenue Report', 'IFRS', { ifrsReference: 'IFRS 15', grouping: 'status' }),
  template('INV-MOV', 'Inventory Movement Report', 'IFRS', { ifrsReference: 'IAS 2', grouping: 'itemCategory' }),
  template('FA-REG', 'Fixed Asset Register', 'IFRS', { ifrsReference: 'IAS 16', grouping: 'assetClass' }),
  template('FA-DEP', 'Depreciation Schedule', 'IFRS', { ifrsReference: 'IAS 16', grouping: 'assetClass' }),
  template('LEASE-LIAB', 'Lease Liability Schedule', 'IFRS', { ifrsReference: 'IFRS 16', grouping: 'leaseContract' }),
  template('AR-AGING', 'Accounts Receivable Aging', 'ACCOUNTING', { grouping: 'agingBucket' }),
  template('AP-AGING', 'Accounts Payable Aging', 'ACCOUNTING', { grouping: 'agingBucket' }),
  template('OCC-RPT', 'Occupancy Report', 'HOTEL_KPI', { kpis: ['occupancy', 'totalGuests', 'roomRevenue'], grouping: 'roomType' }),
  template('ADR-RPT', 'ADR Report', 'HOTEL_KPI', { kpis: ['adr', 'roomRevenue', 'occupancy'], grouping: 'roomType' }),
  template('REVPAR-RPT', 'RevPAR Report', 'HOTEL_KPI', { kpis: ['revpar', 'adr', 'occupancy'], grouping: 'roomType' }),
  template('ROOM-REV', 'Room Revenue Report', 'HOTEL_KPI', { kpis: ['roomRevenue', 'adr', 'revpar'], grouping: 'roomType' }),
  template('GUEST-LEDGER', 'Guest Ledger Report', 'HOTEL_KPI', { grouping: 'guestName' }),
  template('RES-RPT', 'Reservation Report', 'HOTEL_KPI', { grouping: 'reservationSource' }),
  template('CHECKIN-RPT', 'Check-in Report', 'HOTEL_KPI', { kpis: ['checkIns', 'totalGuests'], grouping: 'roomType' }),
  template('CHECKOUT-RPT', 'Check-out Report', 'HOTEL_KPI', { kpis: ['checkOuts', 'totalGuests'], grouping: 'roomType' }),
  template('NOSHOW-RPT', 'No-show Report', 'HOTEL_KPI', { kpis: ['noShows'], grouping: 'reservationSource' }),
  template('CANCEL-RPT', 'Cancellation Report', 'HOTEL_KPI', { kpis: ['cancellations'], grouping: 'reservationSource' }),
  template('HK-STATUS', 'Housekeeping Status Report', 'HOTEL_KPI', { grouping: 'status' }),
  template('ROOM-AVAIL', 'Room Availability Report', 'HOTEL_KPI', { grouping: 'roomType' }),
  template('REST-SALES', 'Restaurant Sales Report', 'POS', { kpis: ['restaurantRevenue', 'vatPayable', 'cashCollection'], grouping: 'outlet' }),
  template('POS-COLL', 'POS Collection Report', 'POS', { kpis: ['cashCollection', 'cardCollection', 'mobileCollection'], grouping: 'paymentMethod' }),
  template('PAY-SUM', 'Payment Summary Report', 'ACCOUNTING', { kpis: ['cashCollection', 'cardCollection', 'mobileCollection'], grouping: 'paymentMethod' }),
  template('DAILY-SALES', 'Daily Sales Report', 'ACCOUNTING', { kpis: ['totalRevenue', 'roomRevenue', 'restaurantRevenue'], grouping: 'department' }),
  template('NIGHT-AUDIT', 'Night Audit Report', 'ACCOUNTING', { kpis: ['totalRevenue', 'cashCollection', 'outstandingReceivable'], grouping: 'department' }),
]

export const sampleRows = [
  {
    slNo: 1, transactionDate: '2025-06-01', documentNo: 'FC-20250601001', voucherNo: 'JV-001',
    reservationNo: 'RES-2025-001', guestId: 'G-0001', guestName: 'John Smith',
    roomNo: '101', roomType: 'Deluxe', department: 'Rooms', costCenter: 'ROOMS',
    accountCode: '4001', accountName: 'Room Revenue', description: 'Direct room charge – 2 nights',
    quantity: 2, rate: 8500, grossAmount: 17000, discount: 500, vat: 1287, serviceCharge: 800,
    netAmount: 18587, debit: 0, credit: 18587, balance: 18587, paymentMethod: 'Card',
    createdBy: 'receptionist', approvedBy: 'manager', status: 'Posted', remarks: '',
  },
  {
    slNo: 2, transactionDate: '2025-06-02', documentNo: 'FC-20250602002', voucherNo: 'JV-002',
    reservationNo: 'RES-2025-002', guestId: 'G-0002', guestName: 'Sara Rahman',
    roomNo: '201', roomType: 'Suite', department: 'Rooms', costCenter: 'ROOMS',
    accountCode: '4001', accountName: 'Room Revenue', description: 'Corporate stay – 3 nights',
    quantity: 3, rate: 12000, grossAmount: 36000, discount: 1800, vat: 2556, serviceCharge: 1500,
    netAmount: 38256, debit: 0, credit: 38256, balance: 38256, paymentMethod: 'Bank Transfer',
    createdBy: 'receptionist', approvedBy: 'manager', status: 'Posted', remarks: 'Corporate rate applied',
  },
  {
    slNo: 3, transactionDate: '2025-06-03', documentNo: 'POS-20250603001', voucherNo: 'JV-003',
    reservationNo: '', guestId: '', guestName: 'Walk-in Customer',
    roomNo: '', roomType: '', department: 'Restaurant', costCenter: 'F&B',
    accountCode: '4010', accountName: 'Restaurant Revenue', description: 'Lunch – Main Restaurant',
    quantity: 4, rate: 1200, grossAmount: 4800, discount: 0, vat: 480, serviceCharge: 240,
    netAmount: 5520, debit: 0, credit: 5520, balance: 5520, paymentMethod: 'Cash',
    createdBy: 'waiter1', approvedBy: '', status: 'Settled', remarks: 'Table 5',
  },
  {
    slNo: 4, transactionDate: '2025-06-03', documentNo: 'PAY-20250603001', voucherNo: 'JV-004',
    reservationNo: 'RES-2025-001', guestId: 'G-0001', guestName: 'John Smith',
    roomNo: '101', roomType: 'Deluxe', department: 'Accounting', costCenter: 'CASHIER',
    accountCode: '1020', accountName: 'Card Collection', description: 'Card payment on checkout',
    quantity: 1, rate: 18587, grossAmount: 18587, discount: 0, vat: 0, serviceCharge: 0,
    netAmount: 18587, debit: 18587, credit: 0, balance: 0, paymentMethod: 'Card',
    createdBy: 'cashier1', approvedBy: 'manager', status: 'Settled', remarks: 'Visa ending 4242',
  },
  {
    slNo: 5, transactionDate: '2025-06-04', documentNo: 'FC-20250604003', voucherNo: 'JV-005',
    reservationNo: 'RES-2025-003', guestId: 'G-0003', guestName: 'Karim Hossain',
    roomNo: '105', roomType: 'Family Villa', department: 'Rooms', costCenter: 'ROOMS',
    accountCode: '4001', accountName: 'Room Revenue', description: 'OTA booking – 4 nights',
    quantity: 4, rate: 9800, grossAmount: 39200, discount: 2000, vat: 2808, serviceCharge: 1600,
    netAmount: 41608, debit: 0, credit: 41608, balance: 41608, paymentMethod: 'Mobile Banking',
    createdBy: 'system', approvedBy: 'manager', status: 'Posted', remarks: 'Booking.com',
  },
  {
    slNo: 6, transactionDate: '2025-06-05', documentNo: 'POS-20250605002', voucherNo: 'JV-006',
    reservationNo: 'RES-2025-002', guestId: 'G-0002', guestName: 'Sara Rahman',
    roomNo: '201', roomType: 'Suite', department: 'Restaurant', costCenter: 'F&B',
    accountCode: '4010', accountName: 'Restaurant Revenue', description: 'Dinner – In-room dining',
    quantity: 2, rate: 2200, grossAmount: 4400, discount: 0, vat: 440, serviceCharge: 220,
    netAmount: 5060, debit: 0, credit: 5060, balance: 5060, paymentMethod: 'Room Charge',
    createdBy: 'waiter2', approvedBy: '', status: 'Posted', remarks: 'Room service',
  },
  {
    slNo: 7, transactionDate: '2025-06-06', documentNo: 'JV-20250606001', voucherNo: 'JV-007',
    reservationNo: '', guestId: '', guestName: '',
    roomNo: '', roomType: '', department: 'Accounting', costCenter: 'ADMIN',
    accountCode: '5010', accountName: 'Salaries Expense', description: 'Monthly payroll – June 2025',
    quantity: 1, rate: 180000, grossAmount: 180000, discount: 0, vat: 0, serviceCharge: 0,
    netAmount: 180000, debit: 180000, credit: 0, balance: -180000, paymentMethod: 'Bank Transfer',
    createdBy: 'accountant', approvedBy: 'director', status: 'Posted', remarks: 'Payroll JV',
  },
  {
    slNo: 8, transactionDate: '2025-06-07', documentNo: 'PAY-20250607002', voucherNo: 'JV-008',
    reservationNo: 'RES-2025-003', guestId: 'G-0003', guestName: 'Karim Hossain',
    roomNo: '105', roomType: 'Family Villa', department: 'Accounting', costCenter: 'CASHIER',
    accountCode: '1030', accountName: 'Mobile Banking Collection', description: 'bKash payment on arrival',
    quantity: 1, rate: 41608, grossAmount: 41608, discount: 0, vat: 0, serviceCharge: 0,
    netAmount: 41608, debit: 41608, credit: 0, balance: 0, paymentMethod: 'Mobile Banking',
    createdBy: 'cashier1', approvedBy: 'manager', status: 'Settled', remarks: 'bKash TxID 0017',
  },
]
